export const musicData = [
    { name: 'Sober' },
    { name: '피었습니다. (Into Bloom)' },
    { name: 'Video Therapy' },
    { name: 'Moonshot' },
    { name: 'Ask' },
    { name: '쉼표 (Comma,)' },
    { name: '지우개 (Undo)' },
    { name: 'You' },
    { name: '파란 배경 (Blue Scene)' },
    { name: '이 별 저 별 (Fate)' },
    { name: '빈집 (Zip.)' },
    { name: '너에게 (To You)' },
    { name: 'Flashback' },
    { name: '네가 내 마음에 자리 잡았다 (Into You)' },
    { name: 'Blue Moon' },
    { name: 'TREE' },
    { name: '폭망 (I Like You)' },
    { name: '그 밤 (The Night)' },
    { name: 'Firefly' },
    { name: '일 (1)' },
    { name: 'Monster' },
    { name: 'Shooting Star' },
    { name: 'STARLIGHT' },
    { name: '아 진짜요. (Oh really.)' },
    { name: 'Autumn Dream' },
    { name: '4242' },
    { name: 'Sunset' },
    { name: '옥탑방 (Rooftop)' },
    { name: '봄이 부시게 (Spring Memories)' },
    { name: '뜨거운 감자' },
    { name: '굿밤 (GOOD BAM)' },
    { name: 'ㅈㅅ (Pardon?)'},
]